//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        internal static string ButtonAboutAppText {
            get {
                return ResourceManager.GetString("ButtonAboutAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonAddText {
            get {
                return ResourceManager.GetString("ButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetically A..Z.
        /// </summary>
        internal static string ButtonAZText {
            get {
                return ResourceManager.GetString("ButtonAZText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook login.
        /// </summary>
        internal static string ButtonFacebookText {
            get {
                return ResourceManager.GetString("ButtonFacebookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually.
        /// </summary>
        internal static string ButtonManuallyText {
            get {
                return ResourceManager.GetString("ButtonManuallyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From new to old.
        /// </summary>
        internal static string ButtonNewOldText {
            get {
                return ResourceManager.GetString("ButtonNewOldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From old to new.
        /// </summary>
        internal static string ButtonOldNewText {
            get {
                return ResourceManager.GetString("ButtonOldNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string ButtonOnlineText {
            get {
                return ResourceManager.GetString("ButtonOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSaveWordText {
            get {
                return ResourceManager.GetString("ButtonSaveWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ButtonSettingsText {
            get {
                return ResourceManager.GetString("ButtonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string ButtonSkipAuthText {
            get {
                return ResourceManager.GetString("ButtonSkipAuthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string ButtonStatisticsText {
            get {
                return ResourceManager.GetString("ButtonStatisticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetically Z..A.
        /// </summary>
        internal static string ButtonZAText {
            get {
                return ResourceManager.GetString("ButtonZAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string EntryOriginalPlaceholder {
            get {
                return ResourceManager.GetString("EntryOriginalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string EntryTranslationPlaceholder {
            get {
                return ResourceManager.GetString("EntryTranslationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add word:.
        /// </summary>
        internal static string LabelAddWordText {
            get {
                return ResourceManager.GetString("LabelAddWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        internal static string LabelChooseLanguageText {
            get {
                return ResourceManager.GetString("LabelChooseLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New word.
        /// </summary>
        internal static string LabelNewWordText {
            get {
                return ResourceManager.GetString("LabelNewWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort words:.
        /// </summary>
        internal static string LabelSortWordsText {
            get {
                return ResourceManager.GetString("LabelSortWordsText", resourceCulture);
            }
        }
    }
}
